### ISSUE TITLE
Build failure on including vite-plugin-vue-markdown

### ISSUE THREAD

**Issue by ajmas** [mdit-vue/vite-plugin-vue-markdown#11] opened 2022-11-02 17:20 UTC
I have been using `vue3-markdown-it`, but because of chunk size issue, I am trying out this project. In replacing dependencies with [vite-plugin-vue-markdown](https://github.com/mdit-vue/vite-plugin-vue-markdown) I now get the following error:

```
'extname' is not exported by __vite-browser-external, imported by node_modules/@rollup/pluginutils/dist/es/index.js
file: /Users/ajmas/Development/my-project/node_modules/@rollup/pluginutils/dist/es/index.js:1:9
1: import { extname, win32, posix, isAbsolute, resolve } from 'path';
            ^
2: import pm from 'picomatch';
/Users/ajmas/Development/my-project/node_modules/rollup/dist/shared/rollup.js:198
        base = Object.assign(new Error(base.message), base);
                             ^

Error: 'extname' is not exported by __vite-browser-external, imported by node_modules/@rollup/pluginutils/dist/es/index.js
    at error (/Users/ajmas/Development/my-project/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/Users/ajmas/Development/my-project/node_modules/rollup/dist/shared/rollup.js:12543:16)
    at Module.traceVariable (/Users/ajmas/Development/my-project/node_modules/rollup/dist/shared/rollup.js:12902:29)
    at ModuleScope.findVariable (/Users/ajmas/Development/my-project/node_modules/rollup/dist/shared/rollup.js:11554:39)
    at FunctionScope.findVariable (/Users/ajmas/Development/my-project/node_modules/rollup/dist/shared/rollup.js:6486:38)
    at ChildScope.findVariable (/Users/ajmas/Development/my-project/node_modules/rollup/dist/shared/rollup.js:6486:38)
    at Identifier.bind (/Users/ajmas/Development/my-project/node_modules/rollup/dist/shared/rollup.js:7553:40)
    at CallExpression.bind (/Users/ajmas/Development/my-project/node_modules/rollup/dist/shared/rollup.js:5383:23)
    at CallExpression.bind (/Users/ajmas/Development/my-project/node_modules/rollup/dist/shared/rollup.js:9049:15)
    at UnaryExpression.bind (/Users/ajmas/Development/my-project/node_modules/rollup/dist/shared/rollup.js:5383:23) {
  code: 'MISSING_EXPORT',
  url: 'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
  id: '/Users/ajmas/Development/my-project/node_modules/@rollup/pluginutils/dist/es/index.js',
  pos: 9,
  loc: {
    column: 9,
    file: '/Users/ajmas/Development/my-project/node_modules/@rollup/pluginutils/dist/es/index.js',
    line: 1
  },
  frame: "1: import { extname, win32, posix, isAbsolute, resolve } from 'path';\n" +
    '            ^\n' +
    "2: import pm from 'picomatch';",
  watchFiles: [
    '/Users/ajmas/Development/my-project/index.html',
    '/Users/ajmas/Development/my-project/.quasar/client-entry.js',
    '/Users/ajmas/Development/my-project/node_modules/vite/package.json',
    '/Users/ajmas/Development/my-project/node_modules/vue/package.json',
    '/Users/ajmas/Development/my-project/node_modules/@quasar/extras/package.json',
    '/Users/ajmas/Development/my-project/node_modules/quasar/package.json',
    '/Users/ajmas/Development/my-project/node_modules/vue/dist/vue.runtime.esm-bundler.js',
    '/Users/ajmas/Development/my-project/node_modules/@quasar/extras/roboto-font/roboto-font.css',
    '/Users/ajmas/Development/my-project/node_modules/@quasar/extras/material-icons/material-icons.css',
    '/Users/ajmas/Development/my-project/node_modules/quasar/dist/quasar.sass',
    ...
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-------------------------------------------------------------------------------------------
```

I am using Quasar with Vite:

```
 Pkg quasar............. v2.10.1
 Pkg @quasar/app-vite... v1.1.3
 Pkg vite............... v2.9.15
```

Node version: v16.10.0

Any idea what could be the issue here?

**Comment by antfu** [comment] 2022-12-30 12:21
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-12-30 12:21 UTC
